In [3]:
!pip install numpy
!pip install pandas
!pip install scikit-learn


     ---------------------------------------- 0.0/341.8 kB ? eta -:--:--
     --------- ----------------------------- 81.9/341.8 kB 4.8 MB/s eta 0:00:01
     --------------------- ---------------- 194.6/341.8 kB 3.0 MB/s eta 0:00:01
     --------------------- ---------------- 194.6/341.8 kB 3.0 MB/s eta 0:00:01
     ------------------------------- ------ 286.7/341.8 kB 1.6 MB/s eta 0:00:01
     -------------------------------------  337.9/341.8 kB 1.5 MB/s eta 0:00:01
     -------------------------------------- 341.8/341.8 kB 1.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.7 MB 3.5 MB/s eta 0:00:04
   - -------------------------------------- 0.4/10.7 MB 4.9 MB/s eta 0:00:03
   -- ------------------------------------- 0.7/10.7 MB 5.4 MB/s eta 0:00:02
   --- ------------------------------------ 1.0/10.7 MB 5.7 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/10.7 MB 5.9 MB/s eta 

In [4]:
!pip install seaborn
!pip install matplotlib


  Using cached seaborn-0.13.0-py3-none-any.whl.metadata (5.3 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
     ---------------------------------------- 0.0/156.8 kB ? eta -:--:--
     ------- -------------------------------- 30.7/156.8 kB ? eta -:--:--
     ------- -------------------------------- 30.7/156.8 kB ? eta -:--:--
     --------------------------- ---------- 112.6/156.8 kB 1.1 MB/s eta 0:00:01
     --------------------------- ---------- 112.6/156.8 kB 1.1 MB/s eta 0:00:01
     ------------------------------------ 156.8/156.8 kB 721.8 kB/s eta 0:00:00
  Using cached pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Using cached seaborn-0.13.0-py3-none-any.whl (294 kB)
   ---------------------------------------- 0.0/7.6 MB ? eta -:--:--
   - -------------------------------------- 0.3/7.6 MB 5.9 MB/s eta 0:00:02
   -- ------------------------------------- 0.6/7.6 MB 5.9 MB/s eta 0:00:02
   ------- -------------------------------- 1.4/7.6 MB 9.8 MB/s eta 0

In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import tensorflow as tf

In [15]:
df = pd.read_csv(r'C:\Users\kushal\Desktop\FINAL_TF2_FILES\TF_2_Notebooks_and_Data\DATA\fake_reg.csv')

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [106]:
df

price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130011   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720992  1001.451646   998.847606
998  403.315576  1000.771023   998.562851
999  599.367093   999.232244  1001.451407

[1000 rows x 3 columns]

In [22]:
df.corr()['price'].sort_values(ascending=False)

price       1.000000
feature2    0.907576
feature1    0.444190
Name: price, dtype: float64

In [24]:
# Convert Pandas to Numpy for Keras

# Features
X = df[['feature1','feature2']].values
X
# Label
y = df['price'].values

# Split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [25]:
scaler=MinMaxScaler()

In [28]:
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [60]:
X_train

array([[0.74046017, 0.32583248],
       [0.43166001, 0.2555088 ],
       [0.18468554, 0.70500664],
       ...,
       [0.54913363, 0.79933822],
       [0.2834197 , 0.38818708],
       [0.56282703, 0.42371827]])

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation

In [72]:
model = Sequential([
    Dense(units=2),
    Dense(units=2),
    Dense(units=2)
])

In [73]:
model = Sequential()

model.add(Dense(2))
model.add(Dense(2))
model.add(Dense(2))

In [74]:
model=Sequential()
model.add(Dense(units=4,activation='relu'))
model.add(Dense(units=4,activation='relu'))
model.add(Dense(units=4,activation='relu'))
model.add(Dense(units=1))

In [75]:
model.compile(optimizer='rmsprop',loss='mse')

In [76]:
model.fit(X_train,y_train,epochs=250)

Epoch 1/250
22/22 [==============================] - 1s 2ms/step - loss: 256713.5156
Epoch 2/250
22/22 [==============================] - 0s 2ms/step - loss: 256689.2344
Epoch 3/250
22/22 [==============================] - 0s 2ms/step - loss: 256667.2188
Epoch 4/250
22/22 [==============================] - 0s 2ms/step - loss: 256645.3438
Epoch 5/250
22/22 [==============================] - 0s 2ms/step - loss: 256623.4531
Epoch 6/250
22/22 [==============================] - 0s 2ms/step - loss: 256601.4844
Epoch 7/250
22/22 [==============================] - 0s 2ms/step - loss: 256579.6875
Epoch 8/250
22/22 [==============================] - 0s 2ms/step - loss: 256557.7188
Epoch 9/250
22/22 [==============================] - 0s 2ms/step - loss: 256535.8125
Epoch 10/250
22/22 [==============================] - 0s 2ms/step - loss: 256513.9844
Epoch 11/250
22/22 [==============================] - 0s 2ms/step - loss: 256492.1406
Epoch 12/250
22/22 [==============================] - 0s 2ms/st

22/22 [==============================] - 0s 2ms/step - loss: 254635.2969
Epoch 97/250
22/22 [==============================] - 0s 2ms/step - loss: 254613.4688
Epoch 98/250
22/22 [==============================] - 0s 2ms/step - loss: 254591.7188
Epoch 99/250
22/22 [==============================] - 0s 2ms/step - loss: 254569.9688
Epoch 100/250
22/22 [==============================] - 0s 2ms/step - loss: 254548.2031
Epoch 101/250
22/22 [==============================] - 0s 1ms/step - loss: 254526.3281
Epoch 102/250
22/22 [==============================] - 0s 1ms/step - loss: 254504.5312
Epoch 103/250
22/22 [==============================] - 0s 2ms/step - loss: 254482.7031
Epoch 104/250
22/22 [==============================] - 0s 2ms/step - loss: 254460.8906
Epoch 105/250
22/22 [==============================] - 0s 2ms/step - loss: 254439.1250
Epoch 106/250
22/22 [==============================] - 0s 2ms/step - loss: 254417.2812
Epoch 107/250
22/22 [==============================] - 0s 1m

22/22 [==============================] - 0s 1ms/step - loss: 252590.0312
Epoch 191/250
22/22 [==============================] - 0s 1ms/step - loss: 252568.2812
Epoch 192/250
22/22 [==============================] - 0s 1ms/step - loss: 252546.6250
Epoch 193/250
22/22 [==============================] - 0s 1ms/step - loss: 252524.8906
Epoch 194/250
22/22 [==============================] - 0s 1ms/step - loss: 252503.1250
Epoch 195/250
22/22 [==============================] - 0s 1ms/step - loss: 252481.3750
Epoch 196/250
22/22 [==============================] - 0s 1ms/step - loss: 252459.7188
Epoch 197/250
22/22 [==============================] - 0s 1ms/step - loss: 252437.9844
Epoch 198/250
22/22 [==============================] - 0s 2ms/step - loss: 252416.2969
Epoch 199/250
22/22 [==============================] - 0s 2ms/step - loss: 252394.7031
Epoch 200/250
22/22 [==============================] - 0s 1ms/step - loss: 252372.9375
Epoch 201/250
22/22 [==============================] - 0s

In [62]:
model.history.history

{'loss': [233211.390625,
  233190.578125,
  233169.78125,
  233148.9375,
  233128.09375,
  233107.265625,
  233086.40625,
  233065.640625,
  233044.796875,
  233023.984375,
  233003.109375,
  232982.234375,
  232961.484375,
  232940.703125,
  232919.84375,
  232899.078125,
  232878.1875,
  232857.46875,
  232836.59375,
  232815.75,
  232794.953125,
  232774.1875,
  232753.390625,
  232732.609375,
  232711.8125,
  232690.96875,
  232670.15625,
  232649.28125,
  232628.484375,
  232607.6875,
  232586.90625,
  232566.078125,
  232545.296875,
  232524.4375,
  232503.703125,
  232482.953125,
  232462.1875,
  232441.328125,
  232420.5,
  232399.75,
  232379.0,
  232358.125,
  232337.34375,
  232316.59375,
  232295.796875,
  232275.046875,
  232254.1875,
  232233.390625,
  232212.640625,
  232191.90625,
  232171.0625,
  232150.328125,
  232129.515625,
  232108.703125,
  232087.9375,
  232067.15625,
  232046.375,
  232025.625,
  232004.84375,
  231984.046875,
  231963.296875,
  231942.515625,


In [51]:
loss = model.history.history['loss']
loss

[240561.515625,
 240540.359375,
 240519.3125,
 240498.109375,
 240476.921875,
 240455.765625,
 240434.625,
 240413.46875,
 240392.28125,
 240371.125,
 240349.96875,
 240328.78125,
 240307.59375,
 240286.484375,
 240265.34375,
 240244.1875,
 240222.953125,
 240201.78125,
 240180.59375,
 240159.515625,
 240138.421875,
 240117.1875,
 240096.046875,
 240074.921875,
 240053.8125,
 240032.65625,
 240011.515625,
 239990.3125,
 239969.234375,
 239948.109375,
 239926.875,
 239905.765625,
 239884.640625,
 239863.515625,
 239842.421875,
 239821.140625,
 239800.0625,
 239779.0,
 239757.78125,
 239736.59375,
 239715.453125,
 239694.375,
 239673.234375,
 239652.0625,
 239630.96875,
 239609.84375,
 239588.796875,
 239567.609375,
 239546.46875,
 239525.390625,
 239504.296875,
 239483.203125,
 239461.984375,
 239440.9375,
 239419.71875,
 239398.578125,
 239377.515625,
 239356.390625,
 239335.3125,
 239314.21875,
 239293.09375,
 239271.953125,
 239250.78125,
 239229.734375,
 239208.578125,
 239187.5,
 2

In [77]:
training_score = model.evaluate(X_train,y_train,verbose=0)
test_score = model.evaluate(X_test,y_test,verbose=0)

In [78]:
training_score

251277.625

In [79]:
test_predictions = model.predict(X_test)

10/10 [==============================] - 0s 1ms/step


In [80]:
test_predictions

array([[5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.50594],
       [5.

In [81]:
test_predictions.shape

(300, 1)

In [92]:
pred_df1=pd.DataFrame(data=y_test,columns=['y-test'])

In [93]:
pred_df2=pd.DataFrame(data=test_predictions,columns=['test_predictions'])

In [96]:
result=pd.concat([pred_df1,pred_df2],axis=1)

In [97]:
result

y-test  test_predictions
0    402.296319           5.50594
1    624.156198           5.50594
2    582.455066           5.50594
3    578.588606           5.50594
4    371.224104           5.50594
..          ...               ...
295  525.704657           5.50594
296  502.909473           5.50594
297  612.727910           5.50594
298  417.569725           5.50594
299  410.538250           5.50594

[300 rows x 2 columns]

In [98]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [99]:
mean_absolute_error(result['y-test'],result['test_predictions'])

494.86939951460334

In [102]:
new_data=[[950,1000]]

In [104]:
new_data=scaler.transform(new_data)

In [105]:
model.predict(new_data)

1/1 [==============================] - 0s 21ms/step


array([[5.50594]], dtype=float32)

In [107]:
from tensorflow.keras.models import load_model

In [108]:
model.save('new_model.h5') 

In [110]:
later_model = load_model('new_model.h5')

In [111]:
later_model.predict(new_data)

1/1 [==============================] - 0s 69ms/step


array([[5.50594]], dtype=float32)